### PR TITLE
Add TableSet.from_xls and TableSet.from_xlsx to return multiple sheets as tables.

### PR DESCRIPTION
**Pull request by jpmckinney**
As mentioned in #8, I don't know where to put these new methods, as TableSet would expect all Excel sheets to have the same structure.

For now, I've put them on TableSet, but a MappedSequence is returned, not a TableSet.

### CODE REVIEW

**Comment by jpmckinney** [comment]
@onyxfish I'd like your input on where to put the new methods for extracting multiple sheets from XLS/XLSX.

**Comment by malcook** [comment]
@jpmckinney  - I'm having trouble following the thread here and wondering if there is a stable release that includes this new --write-sheets option or might it be released soon?  Thx

**Comment by jpmckinney** [comment]
@malcook Not yet, I'm waiting for input from @onyxfish as I'm not 100% confident in my choice of implementation (though this branch works).

**Comment by malcook** [comment]
Thanks, I was wondering if that was not the choke point.

FWIW – if you adopt the format of appending the multiple sheets into a single stream so as to no violate the piping ethos, then, making the recipricol arrangement and allow the csv2sql to build or populate multiple database tables would be just perfect.

FWIW2 – I would prefer that files be named after sheetnames (sanitized, of course, with a common prefix defaulting to the basename of the excel workbook.

Thanks for the tool.  Using it lots.  Would be nice if –verbose presented the inferred ‘create table’ statement on stderr.

~Malcolm Cook

**Comment by jpmckinney** [comment]
Hmm, not sure how we can pipe multiple sheets - the sheets most likely don't follow the same schema, and it's not clear how people would use that.

Please open an issue on csvkit about naming the files. I'm not sure what you mean by `--verbose` for the inferred create table statement. Please open an issue on csvkit with steps to reproduce.

**Comment by jpmckinney** [comment]
ping @onyxfish for feedback since you seem to be reviewing issues :)

Btw, I could use releases of agate-excel, agate-sql, and csvkit - preferably with this merged and https://github.com/wireservice/csvkit/pull/783

**Comment by onyxfish** [comment]
Hey, I looked this over. I see what you mean about TableSet and I think you're right—it doesn't really belong there. I guess my question is: Is there a compelling reason this logic needs to live inside this module rather than the user (or csvkit) simply invoking the `Table.from_xls` multiple times?

If there is, I guess I would argue for overloading the `Table.from_xls` classmethod to return a `MappedSequence` if multiple sheets are specified. That's roughly parallel to how e.g. `Table.aggregate` works, so there is at least some precedent for it.

**Comment by onyxfish** [comment]
@jpmckinney agate-sql release done.

**Comment by jpmckinney** [comment]
@onyxfish I don't mind where it lives, but you created #8 which suggests you wanted it here :)

**Comment by onyxfish** [comment]
Yeah I was thinking about the parallel case to `TableSet.from_csv` where you have sheets with identical structures, which I do think we should support at some point, but is pretty rare in my experience.

**Comment by jpmckinney** [comment]
I've implemented the overloading now.

**Pull request merged**
